### PR TITLE
Feature/directory tree

### PR DESCRIPTION
**Pull request by frolovsa**
suggested initial directory structure
closes issue #1

### CODE REVIEW

**Comment by jswhit** [comment]
how will we handle non-bufr data, like IMS snow cover GRIB and tcvitals text files?

**Comment by frolovsa** [comment]
@HenryWinterbottom-NOAA take a look at the proposed directory tree structure for the clean bucket. your input would be appreciated.

**Comment by frolovsa** [comment]
> how will we handle non-bufr data, like IMS snow cover GRIB and tcvitals text files?

I would imagine we would store it in something like 
reanalysis/snow/ims/yyyy/mm/grib

The addition of the last directory is new. NASA doesn't have it. I figure we might needed it in case we need to store data in several formats. I also imagine we would want to store auxiliary data like png images with data coverage in each file, etc.

**Comment by HenryRWinterbottom** [comment]
> how will we handle non-bufr data, like IMS snow cover GRIB and tcvitals text files?

@jswhit I would suggest we have a sub-directory structure as follows for the respective file types above.

GRIB: `/grib`

TCVitals: `/syndat` -- this is the NCEP convention and will allow us to differentiate between synoptic TC-vitals and/or the hourly CIMSS derived TCVs (if we wish to maintain this capability)

Non-bufr: `/obs` -- I think this is generic enough to be used for all non-standard file types; we could potentially do something like `/obs_nc` if we wanted to further partition into file types (i.e., netcdf).

**Comment by HenryRWinterbottom** [comment]
> > how will we handle non-bufr data, like IMS snow cover GRIB and tcvitals text files?
> 
> I would imagine we would store it in something like reanalysis/snow/ims/yyyy/mm/grib
> 
> The addition of the last directory is new. NASA doesn't have it. I figure we might needed it in case we need to store data in several formats. I also imagine we would want to store auxiliary data like png images with data coverage in each file, etc.

@frolovsa I like this idea. Segregating the file format types is the best path forward IMHO. Otherwise the buckets could potentially become what we have now on BDP (a mess).

**Comment by HenryRWinterbottom** [comment]
Approved.

**Review by HenryRWinterbottom — APPROVED** [review]

**Pull request merged**
